/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js", "./css/input.css"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e2e1",
        "surface-container-high": "#2a2a29",
        "surface-dim": "#131313",
        "surface-tint": "#8ed0e8",
        "secondary-container": "#474746",
        error: "#ffb4ab",
        "surface-container": "#20201f",
        "on-error-container": "#ffdad6",
        "on-secondary": "#303030",
        "primary-container": "#a4e6ff",
        "on-primary-container": "#1f697e",
        outline: "#899296",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#626060",
        "surface-bright": "#393939",
        "surface-container-low": "#1c1b1b",
        secondary: "#c8c6c5",
        surface: "#131313",
        "outline-variant": "rgba(255, 255, 255, 0.1)",
        "tertiary-container": "#dfdcdb",
        "glass-bg": "rgba(18, 18, 18, 0.8)",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#1b667c",
        primary: "#f1faff",
        background: "#131313",
        "on-surface-variant": "#bfc8cc",
        "glow-accent": "rgba(164, 230, 255, 0.3)",
        "on-primary": "#003543",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        display: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        display: ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
